# Generated by Django 6.0.3 on 2026-04-01 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('publication_year', models.CharField(max_length=255)),
                ('edition', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('number_of_pages', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('Genre', models.CharField(max_length=255)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='books')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
