# Generated by Django 6.0.3 on 2026-04-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='external_id',
        ),
    ]
